#!/bin/bash

###########################################################
# pretty~

BLACK=`printf "\033[90m"`
RED=`printf "\033[91m"`
GREEN=`printf "\033[92m"`
YELLOW=`printf "\033[93m"`
BLUE=`printf "\033[94m"`
PURPLE=`printf "\033[95m"`
CYAN=`printf "\033[96m"`
WHITE=`printf "\033[97m"`
RESET=`printf "\033[0m"`

###########################################################
# misc env variables

export GOPATH=$HOME/.gocode
export EDITOR=vim
export TZ=Europe/London


###########################################################
# exit if we're being called from a script; only do settings
# for interactive mode

[ -z "$PS1" ] && return


###########################################################
# keychain

# ssh does this sensibly now, prompting on first connect
#if [ \`whoami\` == "shish" ] && [ "x$SSH_AGENT_PID" == "x" ] && [ -f ~/.ssh/id_dsa ] ; then
#	keychain -q ~/.ssh/id_dsa
#	. ~/.keychain/\`hostname\`-sh
#fi

#if [ -n "$GNOME_KEYRING_PID" ] && [ -f ~/.ssh/id_rsa ] ; then
#	eval $(gnome-keyring-daemon --start)
#	export SSH_AUTH_SOCK
#fi


###########################################################
# common aliases

if [ `uname -s` == "SunOS" ] ; then
	alias 'ls'='gnuls --color=auto'
elif [ `uname -s` == "Darwin" ] ; then
	export CLICOLOR=1
	export LSCOLORS=ExFxBxDxCxegedabagacad
else
	alias 'ls'='ls --color=auto'
fi

alias 'l'='ls'
alias 'll'='ls -golh'
alias 'less'='less -r'
alias 'rm'='rm -i'
alias 'mv'='mv -i'
alias 'cp'='cp -i'
alias 'which'='type -p'


###########################################################
# a pretty prompt
 
C1='\[\e[01;33m\]'
C2='\[\e[01;37m\]'
C3='\[\e[00;33m\]'
C4='\[\e[00m\]'

XTITLE='\e]2;\u@\H -- \w\a'
if [ "$DISPLAY" == "" ] ; then
        XTITLE=''
fi
PS1=$XTITLE$C2'['$C1'\u'$C2'] on ['$C1'\h'$C2'] '$C2'\d \T'$NONE$C3' \w\n\$ '$C4''
PS2=$C2'['$C1'more info needed'$C2']\n'$C4''


 
###########################################################
# add personal program and manual folders if they exist

[[ -f /etc/bash_completion             ]] && . /etc/bash_completion


###########################################################
# shell options

shopt -s cdspell
shopt -s dirspell
shopt -s checkhash
shopt -s histappend
shopt -s checkwinsize
shopt -s no_empty_cmd_completion
export PROMPT_COMMAND='history -a'
export HISTCONTROL=ignoreboth
export HISTSIZE=
export HISTFILESIZE=
export HISTTIMEFORMAT="%F %T -- "
export HISTFILE="$HOME/.bash_eternal_history"


###########################################################
# company / site specific things

if [ -f ~/.local_profile.sh ] ; then
	. ~/.local_profile.sh
fi


###########################################################
# say hello

if md5sum -c ~/.motd.seen ; then
    MSG=`fortune`
else
    MSG=`cat /etc/motd`
    md5sum /etc/motd > ~/.motd.seen
fi

clear
if [ ! -z "$MSG" ] ; then
    echo 
    echo "$MSG"
    echo
    echo "                    ==========                    =========="
    echo
fi
