syntax enable
filetype plugin on
set autoindent
set autowrite
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set backspace=indent,eol,start	" more powerful backspacing
set ruler
set title
set hlsearch
set foldmethod=marker
set mouse-=a   " don't do clever mouse things
set colorcolumn=81,101 " absolute columns to highlight "
set colorcolumn=+1,+21 " relative (to textwidth) columns to highlight "
set autoread   " update when a file is changed from outside
set wildmenu

" When editing a file, always jump to the last cursor position
autocmd BufReadPost *
\ if line("'\"") > 0 && line ("'\"") <= line("$") |
\   exe "normal! g'\"" |
\ endif

" file type stuff
autocmd FileType * set tabstop=4|set shiftwidth=4|set noexpandtab
autocmd FileType python set tabstop=4|set shiftwidth=4|set expandtab|set softtabstop=4
autocmd FileType renpy set tabstop=4|set shiftwidth=4|set expandtab|set softtabstop=4
autocmd BufNewFile,BufRead *.mako setlocal ft=mako
let python_highlight_all = 1

" custom keys
map <F5> :bp<CR>
map <F6> :w<CR>
map <F8> :bn<CR>
