syntax enable
filetype plugin on
set autoindent
set autowrite
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set backspace=indent,eol,start	" more powerful backspacing
set ruler
set title
set hlsearch
set foldmethod=marker
if v:version >= 700
	set spelllang=en_gb
	set spellfile=~/.vimspell.en_gb.add
	set spellfile=~/.vimspell.add
endif

autocmd FileType * set tabstop=4|set shiftwidth=4|set noexpandtab
autocmd FileType python set tabstop=4|set shiftwidth=4|set expandtab|set softtabstop=4
autocmd FileType renpy set tabstop=4|set shiftwidth=4|set expandtab|set softtabstop=4

" When editing a file, always jump to the last cursor position
autocmd BufReadPost *
\ if line("'\"") > 0 && line ("'\"") <= line("$") |
\   exe "normal! g'\"" |
\ endif

autocmd BufNewFile,BufRead *.mako setlocal ft=mako
let python_highlight_all = 1

" Removes trailing spaces
function TrimWhiteSpace()
  %s/\s*$//
  ''
:endfunction

map <F5> :bp<CR>
map <F6> :w<CR>
map <F8> :bn<CR>
map <F2> :call TrimWhiteSpace()<CR>
map! <F2> :call TrimWhiteSpace()<CR>
