#!/bin/bash

# make sure the file exists for grepping
if [ ! -f ~/.ssh/authorized_keys2 ] ; then
	echo -n > ~/.ssh/authorized_keys2
fi

if [ -f $SLEK_PRIVATE/ssh.hostconfigs ] ; then
	cat $SLEK_PRIVATE/ssh.hostconfigs >> ~/.ssh/config
fi

if [ -f $SLEK_PRIVATE/ssh.knownhosts ] ; then
	cat $SLEK_PRIVATE/ssh.knownhosts | grep AAAA | sed -E "s/\s+/ /" > ~/.ssh/known_hosts
	ssh-keygen -H >/dev/null 2>&1
	rm -f ~/.ssh/known_hosts.old
fi

chmod 700 ~/.ssh
chmod 600 ~/.ssh/*
