#!/bin/bash

# make this bit explicitly personal, for anyone who forks the repo
if [ `whoami` == "shish" ] ; then
	# remove 2007 "login from ryoku" if it exists
	if grep -q PpnOttseBrDcioL9Sy56RW ~/.ssh/authorized_keys2 ; then
		echo "Removing 2007 ssh key"
		cat ~/.ssh/authorized_keys2 | grep -v PpnOttseBrDcioL9Sy56RW > ~/.ssh/authorized_keys2.new
		mv ~/.ssh/authorized_keys2.new ~/.ssh/authorized_keys2
	fi

	# append "login from min" if it doesn't exist
	if ! grep -q ULyi261I2LdNxAcbO8PiYa ~/.ssh/authorized_keys2 ; then
		echo "Adding 2010 ssh key"
		cat >> ~/.ssh/authorized_keys2 <<EOD
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAuA+1+jzP6/vqsu9UefHOEnHAMUHL4BoKZiRJDzULyi261I2LdNxAcbO8PiYaQHOdDfMq5JUzEiD4EJY7yJnwmvMKnEGGw/Kuf1zNMtdAUX5fsxTBALWAm2l5NiACXDvjXe7SO3Nf52L+E59FZLqla/Syd7SsAtj1VaQurOH9kjpQMK9DoOmZ7uVOhuy205/tNFogKYkbPAKiHRAVkpWln0WiEy7JGi80pQR3QMTURSn2RpFPj+o2qhGviNi8dBQ7E/K329gXwhqaX5AsKlBSJMzG+uNX7mfF/xf6wn6xWrJrF98EU6XA7NSg/Msjgt7UlDkCC2F8lcjOgkSRKzAe+w== shish@min [2010 key]
EOD
	fi
fi
